# escape=`
FROM microsoft/windowsservercore:10.0.14393.1480
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Install-PackageProvider -Name chocolatey -RequiredVersion 2.8.5.130 -Force; `
    Install-Package -Name microsoft-build-tools -RequiredVersion 15.0.26320.2 -Force; `
    Install-Package -Name netfx-4.6.2-devpack -RequiredVersion 4.6.01590 -Force; `
    Install-Package -Name webdeploy -RequiredVersion 3.5.2 -Force

 RUN Install-Package -Name nuget.commandline -RequiredVersion 3.4.3 -Force; `
    & C:\Chocolatey\bin\nuget install MSBuild.Microsoft.VisualStudio.Web.targets -Version 14.0.0.3

ENTRYPOINT ["powershell"]