# escape=`
From msbuild:netfx-4.7.1

WORKDIR c:\InternalApplications\trunk\SharedComponents\Content
COPY .\trunk\SharedComponents\Content\ .

RUN nuget restore -ConfigFile Nuget.Config

 RUN msbuild ContentWCF.sln /p:OutputPath=c:\out `
         /p:DeployOnBuild=true /p:VSToolsPath=C:\MSBuild.Microsoft.VisualStudio.Web.targets.14.0.0.3\tools\VSToolsPath

