# escape=`
FROM msbuild:netfx-4.5.2-ssdt as builder

WORKDIR C:\trunk
COPY .\trunk .
RUN msbuild .\_databases\WebContentDB\WebContent\WebContentDB.sqlproj `
    /p:SQLDBExtensionsRefPath="C:\Microsoft.Data.Tools.Msbuild.10.0.61026\lib\net40" `
    /p:SqlServerRedistPath="C:\Microsoft.Data.Tools.Msbuild.10.0.61026\lib\net40"

# db image
FROM microsoft/mssql-server-windows-express:2016-sp1-windowsservercore-10.0.14393.1715

ENV ACCEPT_EULA="Y" `
    DATA_PATH="C:\data" `
    sa_password="DockerCon!!!"

VOLUME ${DATA_PATH}
WORKDIR C:\trunk

COPY Docker\Initialize-Database.ps1 .
CMD powershell ./Initialize-Database.ps1 -sa_password $env:sa_password -data_path $env:data_path -Verbose

COPY --from=builder C:\trunk\_Databases\WebContentDB\WebContent\bin\Output .
COPY --from=builder C:\trunk\_Databases\TypeDataPacker .\TypeDataPacker
COPY --from=builder C:\trunk\_Databases\WebContentDB\WebContent\TypeData .\TypeData